"""Add VisualSurvey open status

Revision ID: 208688373b26
Revises: 3b6ad7ed0d11
Create Date: 2025-09-29 23:06:27.646082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '208688373b26'
down_revision: Union[str, Sequence[str], None] = '3b6ad7ed0d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visual_surveys', sa.Column('is_open', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('visual_surveys', 'is_open')
    # ### end Alembic commands ###
