"""Add confidence property to object register

Revision ID: 3b6ad7ed0d11
Revises: d18402d04fce
Create Date: 2025-09-28 18:04:17.663355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3b6ad7ed0d11'
down_revision: Union[str, Sequence[str], None] = 'd18402d04fce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('object_registers', sa.Column('confidence', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('object_registers', 'confidence')
    # ### end Alembic commands ###
