"""Initial migration - add pavement module

Revision ID: d18402d04fce
Revises: 
Create Date: 2025-09-28 17:37:24.807224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd18402d04fce'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('road_stretchs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('lat_initial', sa.Float(), nullable=True),
    sa.Column('long_initial', sa.Float(), nullable=True),
    sa.Column('lat_final', sa.Float(), nullable=True),
    sa.Column('long_final', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visual_surveys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('suyvey_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stretch_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['stretch_id'], ['road_stretchs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('visual_registers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('long', sa.Float(), nullable=True),
    sa.Column('survey_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['survey_id'], ['visual_surveys.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('object_registers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('class_type', sa.Integer(), nullable=False),
    sa.Column('coord_x1', sa.Integer(), nullable=False),
    sa.Column('coord_y1', sa.Integer(), nullable=False),
    sa.Column('coord_x2', sa.Integer(), nullable=False),
    sa.Column('coord_y2', sa.Integer(), nullable=False),
    sa.Column('visual_register_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['visual_register_id'], ['visual_registers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('object_registers')
    op.drop_table('visual_registers')
    op.drop_table('visual_surveys')
    op.drop_table('road_stretchs')
    # ### end Alembic commands ###
